site_name: SSVC Open Connect
site_url: https://SSVC0059.github.io/ssvc_open_connect/

site_author: thedemoncat
site_description: >-
 Модуль расширения функционала автоматики отбора для ректификации  SSVC0059V2,

repo_name: SSVC0059/ssvc_open_connect
repo_url: https://github.com/SSVC0059/ssvc_open_connect


theme:
  name: material
  logo: media/logo.png
  favicon: media/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - toc.integrate
    - navigation.top
    - content.code.copy


nav:
  - Главная: 
      - index.md
      - disclaimer.md
  - "Подготовка":
      - preparation/controller.md
      - preparation/driver.md
      - preparation/firmware.md
      - preparation/flasher.md
      - preparation/adafruit_webserial_esptool.md
  - "Интерфейсы и Периферия" : 
      - usage/interfaces/power.md
      - usage/interfaces/uart.md
      - usage/interfaces/ds18b20.md
      - usage/interfaces/rgb_led.md
      - usage/interfaces/pin_out.md
      - usage/interfaces/bmp581.md
  - "Руководство пользователя":
      - usage/get_started.md
      - usage/user_management.md
      - usage/troubleshooting.md
  - "Калькулятор ректификации":
      - calculator/index.md
      - calculator/manual.md
  - "Готовые модули":
      - ready_made/mini.md
      - ready_made/din_version.md
      - ready_made/inside_version.md
  - Для разработчиков: 
      - develop/gettingstarted.md
      - develop/build.md
      - develop/codedump.md
      - develop/mkdocs.md
      - develop/ssvc_uart_api_docs.md
      
  - "FAQ" : 
      - faq/check_list.md
      - faq/faq.md
  - "Прочее" :
      - info/changelog.md

# Add custom CSS for MoonLight styling
extra_css:
  - stylesheets/openconnect.css
  - stylesheets/calculator.css

extra_javascript:
  - javascripts/openconnect.js

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
      
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thedemoncat
  consent:
    title: Cookie consent
    description: >-
      Сайт использует cookie-файлы, чтобы сделать ваше пребывание на нём максимально удобным. 
      Оставаясь на сайте, вы даёте своё согласие на использование cookie-файлов.
    actions:
      - accept
      - reject
  analytics:
    provider: google
    property: G-TE0KVENQEE  # Ваш ID Google Analytics

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - autorefs
  - literate-nav:
      nav_file: README.md
      implicit_index: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: false
            show_signature_annotations: true

copyright: |
  Copyright &copy; 2025 by <a href="https://github.com/thedemoncat"  target="_blank" rel="noopener">demoncat</a> -
  <a href="#__consent">Изменить настройки файлов cookie</a>